### ISSUE TITLE
module initialization error

### ISSUE THREAD

**Issue by amitaymolko** [FidelLimited/serverless-plugin-optimize#33]
After adding the plugin i get this error in CloudWatch when calling any Lambda function:
```
module initialization error: Error
at Error (native)
at Object.fs.lstatSync (fs.js:839:18)
at Object.realpathSync (fs.js:1443:21)
at PATH.js:60409:38
at Array.map (native)
at Object.<anonymous> (PATH.js:60408:3)
at Object.291.fs (PATH.js:60539:4)
at s (PATH.js:1:683)
at PATH.js:1:734
at Object.278.PATH.js:57841:16)
```

This seems to caused by these lines in Uglify.js:
```

var FILES = exports.FILES = [
    "../lib/utils.js",
    "../lib/ast.js",
    "../lib/parse.js",
    "../lib/transform.js",
    "../lib/scope.js",
    "../lib/output.js",
    "../lib/compress.js",
    "../lib/sourcemap.js",
    "../lib/mozilla-ast.js"
].map(function(file){
    return path.join(path.dirname(fs.realpathSync(__filename)), file);
});
```

**Comment by goncaloneves** [comment]
@amitaymolko Module initialization error happens when the lambda path is not set correctly for the handler. Share one of the failing functions lambda path in `serverless.yml` and your optimize debug output.

Other than that if Uglify is the root cause, is optimize babelifying the code correctly before uglify? Set minify to `false` and debug to `true` and check the optimize bundle in `_optimize`folder.

**Comment by amitaymolko** [comment]
@goncaloneves I found that the cause of the issue was that `jade` had `Uglify` as a `dependancy` and not a `devDependancy`.
Moving over to `pug` fixed the issue
