### ISSUE TITLE
BUG: feeded variables

### ISSUE THREAD

**Issue by iOSonntag** [FidelLimited/serverless-plugin-optimize#43]
The optimizer-plugin will never kick in if your yml looks like this
```
provider:
    ...
    runtime: "${self:custom.NODE_JS_RUNTIME}"
custom:
    ...
    NODE_JS_RUNTIME: nodejs6.10
```
The reason is that in the index.js constructor the runtime will be recieved as: ${self:custom.NODE_JS_RUNTIME}, wich causes the plugin to stop right away.

I don't know much about the whole thing tho, but I guess this can be setup in another way or?

**Comment by goncaloneves** [comment]
You always need `name` and `runtime` defined in the provider.
There is a Serverless open issue about this: https://github.com/serverless/serverless/issues/3356.

The only way I see is for the plugin to trigger the variable parsing logic itself, but is redundancy and quite a stretch for something that is an configuration file change.

Either someone picks up and builds a solution for this or we will wait for SLS to add this enhancement, that I believe won't be done anytime soon due to the overall change in the plugin event/validation logic.

Closed for the time being.
